package view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class CategoryForm extends JPanel {
    private JPanel listPanel;
    private JScrollPane scrollPane;
    private JPanel mainPanel;
    private final List<JCheckBox> checkBoxList = new ArrayList<>();

    public CategoryForm() {
        $$$setupUI$$$();
        initList();
        this.add(mainPanel);
        this.setVisible(true);
    }

    public List<JCheckBox> getCheckBoxList() {
        return checkBoxList;
    }


    // TODO: реализовать получение категорий
//    public Set<entity.Category> getCategories() {
//        Set<entity.Category> categories = new HashSet<>();
//
//        checkBoxList.forEach(category -> {
//            if (category.isSelected()) {
//                categories.add(new Category(category.getText()));
//            }
//        });
//
//        return categories;
//    }

    private void initList() {
        // TODO: получать категории из бд
        String[] categories = new String[]{"1", "2", "3"};

        for (String category : categories) {
            JCheckBox checkBox = new JCheckBox(category);
            listPanel.add(checkBox);
            checkBoxList.add(checkBox);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setAutoscrolls(true);
        scrollPane = new JScrollPane();
        scrollPane.setAutoscrolls(true);
        scrollPane.setMaximumSize(new Dimension(200, 40));
        scrollPane.setVerifyInputWhenFocusTarget(true);
        scrollPane.setVerticalScrollBarPolicy(20);
        mainPanel.add(scrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        listPanel.setAutoscrolls(true);
        listPanel.setInheritsPopupMenu(false);
        listPanel.setMaximumSize(new Dimension(-1, -1));
        scrollPane.setViewportView(listPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        listPanel = new JPanel(new GridLayout(0, 1));
    }
}